exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    ".venv",
    "venv",
    ".idea",
]

line-length = 88
indent-width = 4
target-version = "py311" # Python 3.11
# output-format = "github"

[lint]
preview = true
select = [
    "A",
    "ANN",
    "ARG",
    "ASYNC",
    "B",
    "C4",
    "COM812", # missing-trailing-comma
    "E",
    "ERA", # commented-out-code
    "F",
    "I",
    "ISC",
    "N",
    "PERF",
    "PIE",
    "PLC0208", # iteration-over-set
    "PLC0414", # useless-import-alias
    "PLC0415", # import-outside-top-level
    "PLC2401", # non-ascii-name
    "PLC2403", # non-ascii-import-name
    "PLE0304", # invalid-bool-return-type
    "PLE0307", # invalid-string-return-type
    "PLE1142", # await outside async
    "PLE1700", # yield-from-in-async-function
    "PLE4703", 	# modified-iterating-set
    "PLR",
    "PLW",
    "Q003", # avoidable-escaped-quote
    "Q004", # unnecessary-escaped-quote
    "RET",
    "SIM",
    "UP003", # type-of-primitive
    "UP008", # super-call-with-parameters
    "UP010", # unnecessary-future-input
    "UP012", # unnecessary-encode-utf8
    "UP015", # redundant-open-modes
    "UP017", # datetime-timezone-utc
    "UP028", # yield-in-for-loop
    "UP029", # unnecessary-builtin-import
    "UP030", # format-literals
    "UP031", # printf-string-formatting
    "UP032", # f-string
    "W",
]

ignore = [
    "B008"
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.isort]
from-first = true
no-sections = false
length-sort = true
relative-imports-order = "closest-to-furthest"
lines-after-imports = 1

[format]
quote-style = "double"
indent-style = "tab"
skip-magic-trailing-comma = true
line-ending = "lf" # unix
docstring-code-format = true
docstring-code-line-length = "dynamic"

[lint.pylint]
max-args = 7
max-positional-args = 3
max-returns = 4
